version: "3.7"
services:
  app:
    build: 
      args: 
        user: xs
        uid: 1000
      context: ./docker
      dockerfile: Dockerfile
    image: xstm
    container_name: xstm-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - xstm

  db:
    image: mongo:latest
    container_name: xstm-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: xs
      MONGO_INITDB_ROOT_PASSWORD: xs@heliostech
    ports:
      - 27019:27017
    volumes:
      - ./db/mongo:/data/db
    networks:
      - xstm

  nginx:
    image: nginx:1.17-alpine
    container_name: xstm-nginx
    restart: unless-stopped
    ports:
      - 8009:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - xstm

networks: 
  xstm:
    driver: bridge
